import { 
    Sparkles as SparklesIcon, 
    Trash2 as TrashIcon, 
    Plus as PlusIcon, 
    Printer as PrinterIcon, 
    Download as DownloadIcon,
    CheckCircle as CheckCircleIcon,
    XCircle as XCircleIcon,
    AlertCircle as AlertCircleIcon,
    TrendingUp as TrendingUpIcon,
    FileText as FileTextIcon,
    Briefcase as BriefcaseIcon,
    GraduationCap as GraduationCapIcon,
    Award as AwardIcon,
    Link as LinkIcon,
    Mail as MailIcon,
    Phone as PhoneIcon,
    MapPin as MapPinIcon,
    Link as LinkedinIcon,
    Globe as GlobeIcon,
    Upload as UploadIcon,
    LogOut as LogOutIcon,
    LogIn as LogInIcon,
    Layout as LayoutIcon
} from 'lucide-react';

export {
    SparklesIcon,
    TrashIcon,
    PlusIcon,
    PrinterIcon,
    DownloadIcon,
    CheckCircleIcon,
    XCircleIcon,
    AlertCircleIcon,
    TrendingUpIcon,
    FileTextIcon,
    BriefcaseIcon,
    GraduationCapIcon,
    AwardIcon,
    LinkIcon,
    MailIcon,
    PhoneIcon,
    MapPinIcon,
    LinkedinIcon,
    GlobeIcon,
    UploadIcon,
    LogOutIcon,
    LogInIcon,
    LayoutIcon
};
